server:
  port: 8888

spring:
  security:
    user:
      name: root
      password: 123456
  application:
    name: security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springsecurity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
      # 逻辑删除key指定
      logic-delete-field: del_flag
  mapper-locations: classpath*:mapper/xml/*.xml
  type-aliases-package: com.fsx.security.entity

logging:
  level:
    org:
      springframework:
        security: DEBUG